[package]
name = "rust_monkey"
version = "0.1.0"
authors = ["Ryan <ryankilbane92@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
